### ISSUE TITLE
Adding import to Android

### ISSUE THREAD

**Issue by BLTowsen** [capacitor-community/camera-preview#103]
When adding the required import to Android it is not finding the package.

I am probably doing it incorrectly but when adding:

```
import com.ahm.capacitor.camera.preview.CameraPreview;


this.init(savedInstanceState, new ArrayList<Class<? extends Plugin>>() {{
      // Additional plugins you've installed go here
      // Ex: add(TotallyAwesomePlugin.class);
      add(CameraPreview.class);
}});
```
It gives an error for the package name.  Is there any extra steps I need to follow before importing the package.

**Comment by BLTowsen** [comment]
I was dumb and didn't realize the package you need to import is in the android folder of the app.

**Comment by zNoobs** [comment]
Can you explain?
Because the package does not exist...
`import com.ahm.capacitor.camera.preview.CameraPreview;
`
