### ISSUE TITLE
Black Screen on iOS - PWA

### ISSUE THREAD

**Issue by Christophe-re** [capacitor-community/camera-preview#113]
**Describe the bug**
The camera not working on Safari and Chrome on IOS 14, I have a black screen.
 This error is in the console :
Unhandled Promise Rejection: NotAllowedError: The request is not allowed by the user agent or the platform in the current context, possibly because the user denied permission.

All is good on Mac Os.

**To Reproduce**

Html : 
<img width="412" alt="Capture d’écran 2021-03-18 à 17 11 18" src="https://user-images.githubusercontent.com/22072618/111658821-fe28bd80-880c-11eb-9474-dc52dbeafa0f.png">

ts : 
<img width="808" alt="Capture d’écran 2021-03-18 à 17 12 38" src="https://user-images.githubusercontent.com/22072618/111659035-2a443e80-880d-11eb-8f5c-c3bfdeea72ff.png">

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone 8]
 - OS: [IOS 14]
 - Browser [safari, chrome]

The application is hosted on https on firebase
I use camera-preview 1.2.0

**Comment by argometric** [comment]
add autoplay and playsinline to the video tag after its generated, this should fix the black screen issue. 

CameraPreview.start({
        position: "rear",
        toBack: true,
        parent: "content",
        heigth: 300,
        width: 400,
        disableAudio: true
      }).then(() => {
        document.getElementById("video")?.setAttribute("playsinline", "true");
        document.getElementById("video")?.setAttribute("autoplay", "true");
      })

that should fix it. I got issue now that the screen on iOs gets stuck every second for a short period of time, like its lagging. If you find a solution for that please let me know.

**Comment by pbowyer** [comment]
Closing this ticket as there's been no recent feedback. Please submit a pull request if code changes are needed, or re-open this ticket.
