### ISSUE TITLE
Fatal error when putting iOS app in the background

### ISSUE THREAD

**Issue by RemyBosviel** [capacitor-community/camera-preview#121]
(if anything is wrong with the way I'm doing this, please tell me: I am very new to programing in general and trying to report bugs to the community in particular).

This occurs when testing an iOS app made with Capacitor on the simulator of xCode.

The options used for camera-preview are:

  cameraPreviewOptions: CameraPreviewOptions = {
      position: 'rear',
      enableHighResolution: true,
      storeToFile: true,
      parent: 'cameraPreview',
      className: 'livePreview',
      disableAudio: true
  }

The app will crash when put into background if the plugin has been called at least once (in my case if the component using the plugin has been used).

In xCode the reported error reads as follows:

    Fatal error: Unexpectedly found nil while implicitly unwrapping an Optional value: file CapacitorCommunityCameraPreview/Plugin.swift, line 43

Following this error, I have made a fix [pull request 122](https://github.com/capacitor-community/camera-preview/pull/122) but it needs to be looked at to make sure everything I added there is necessary (as I am unsure about how everything works)... Also I think we might need to add the same fix line 30 of the same file for other cases.

**Comment by pbowyer** [comment]
Closing as your pull request was merged. Thanks for your contributions! 👍
