### ISSUE TITLE
capacitor version depencies

### ISSUE THREAD

**Issue by bialabs** [capacitor-community/camera-preview#140]
**Describe the bug**
In my project i'm using capacitor 2.4.7, but npm downloads version 3.0 dependecy because in the package.json of this package is specified "latest". This causes typescript errors like "Interface 'CapacitorInstance' incorrectly extends interface 'CapacitorGlobal'"
For now i've fixed by setting manually 2.4.7 instead of 3.0 in package-lock.json under camerapreview -> dependencies

I think it should be fixed like[ other plugins did](https://github.com/martinkasa/capacitor-secure-storage-plugin/commit/b8eb1d8aa0c1b06a1af778cadbc2feb70f6ebe19#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519)
 
**To Reproduce**
Install camera preview in a capacitor 2 project

**Comment by anth0** [comment]
@bialabs You are right. Please submit a PR.

**Comment by Mathyn** [comment]
I've added a PR https://github.com/capacitor-community/camera-preview/pull/146

**Comment by bialabs** [comment]
@Mathyn in [this commit](https://github.com/martinkasa/capacitor-secure-storage-plugin/commit/b8eb1d8aa0c1b06a1af778cadbc2feb70f6ebe19#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519) i see fixes also in the /ios folder. Do you think are needed also for this plugin?

**Comment by Mathyn** [comment]
Good one. I did a quick check:

`ios/Podfile.lock` -> shows version 2.0.1 currently, this one has not been updated for some time. It might be fine but someone might need to test this (don't have a Macbook at hand).

Bunch of files in `ios/Pods` were changed but this directory does not exist for this project by default

**Comment by bialabs** [comment]
Yeah, for this reason i didn't added a PR
@arielhernandezmusa can you check?

**Comment by sinkingtitanic** [comment]
@Mathyn I tested your PR and it works. @bialabs please merge 

For anyone who wants a quick fix until authors merge, just install @Mathyn [PR](https://github.com/Mathyn/camera-preview): 
```
npm uninstall @capacitor-community/camera-preview
npm install git+https://github.com/Mathyn/camera-preview.git
```

That's all folks!

**Comment by Kaoschuks** [comment]
I have created a repo here that uses this plugin and other methods for getting camera data

https://github.com/Kaoschuks/ionic-media-editor

Please review

**Comment by pbowyer** [comment]
Closing as this was fixed.
