### ISSUE TITLE
captureSample is not a function

### ISSUE THREAD

**Issue by fr3shn3ss** [capacitor-community/camera-preview#142]
**Describe the bug**
Uninstalled and installed the latest version (1.2.1) using npm.  

"captureSample" function does not exist in "node_modules\@capacitor-community\camera-preview\android\src\main\java\com\ahm\capacitor\camera\preview\CameraPreview.java" 

Capacitor version: 
    "@capacitor/android": "^2.1.2",
    "@capacitor/core": "2.1.2",

I understand that the latest NPM version doesn't have the captureSample function. How can I install Master. I tried a many different solutions and none of them worked

**Comment by ufocruz** [comment]
Same problem

**Comment by ufocruz** [comment]
at the moment, my work arround is installing with this command:
`npm install git+https://github.com/capacitor-community/camera-preview.git`

**Comment by hodeware** [comment]
> at the moment, my work arround is installing with this command:
> `npm install git+https://github.com/capacitor-community/camera-preview.git`

That saved me days. Hi Guys, is it possible to publish that to the NPM, please?

**Comment by jcesarmobile** [comment]
Can't reproduce on version 4 of the plugin
