### ISSUE TITLE
Zoom

### ISSUE THREAD

**Issue by glancel** [capacitor-community/camera-preview#143]
Hello everyone!

I love this plugin and I would like to thank anyone who contributed to the project.
Has anyone experimented with something I could work on for the zoom feature?

Thank you

**Comment by mehdis34** [comment]
Hi,
 I have the same problem as you.
 Have you found a solution?

**Comment by glancel** [comment]
Actually no, but it's an important feature but I can't get it to work... If you find any alternative solution please let me know.

**Comment by Alfer-Star** [comment]
There is a Cordova Plugin which is like this one and has zoom.
See also #99 
Last time (in march 2021) I tested, the to-back feature does not work correctly with capacitor.

**Comment by lauritaila** [comment]
is the height and width if you erase that in yhe CameraPreviewOptions the camera should look fine.

**Comment by pbowyer** [comment]
Hi everyone, pinch and zoom is now available in version 2.1.0 released today. Good luck using it!
