### ISSUE TITLE
Image is getting blurred in one-plus phone 

### ISSUE THREAD

**Issue by iamtarun1993** [capacitor-community/camera-preview#147]
**Describe the bug**
Image is getting blurred in the one-plus phone when flash mode is set to "off".

**To Reproduce**
When I set the flash mode to "on" then pictures are Good, but when I set this to "off" then pictures are getting blurred 

I'm using this version
`"@capacitor-community/camera-preview": "^1.0.6",`

**Comment by Julias0** [comment]
Upgrading to capacitor 3 fixes this

**Comment by pbowyer** [comment]
I'm sorry but without this model of phone to hand there's not much I can do to help. I do see a lot of variation between the focus quality of photos captured on different phones, but nothing pointing to an issue.
