### ISSUE TITLE
Compilation error [Interface 'CapacitorInstance' incorrectly extends interface 'CapacitorGlobal'.]

### ISSUE THREAD

**Issue by ncham** [capacitor-community/camera-preview#150]
**Describe the bug**
I get this error when compiling my ionic, angular project.

**To Reproduce**
"@capacitor/cli": "^2.4.7",
"@capacitor/core": "^2.4.7",
"@capacitor-community/camera-preview": "^1.2.1",

**Screenshots**
<img src="https://imgur.com/xcJno5D.jpeg"/>

**Desktop (please complete the following information):**
 - OS: [windows 10]
 - Browser [Chrome]

**Additional context**

**Comment by ncham** [comment]
After adding this issue only I saw others also had the same problem.
Sorry for adding a duplicated issue, hope you guys will fix this soon. Thanks in advance.

**Comment by Julias0** [comment]
For a quick fix add
```
 "skipLibCheck": true
```

to tsconfig.json under compilerOptions

**Comment by Kaoschuks** [comment]
I have created a repo here that uses this plugin and @Julias0  answer and other basic capacitor methods for getting camera data

https://github.com/Kaoschuks/ionic-media-editor

Please review

**Comment by pbowyer** [comment]
I'm closing as we now target Capacitor 3. If this issue happens again please open a new ticket.
