### ISSUE TITLE
Capacitor 3 Not Compatible - Solved

### ISSUE THREAD

**Issue by meforce** [capacitor-community/camera-preview#151]
Capacitor 3 Not Compatible. Will this support?

**Comment by darbanhandrew** [comment]
Hi, I found a work around to use this in the web, but i am a newbie in git i don't know how to share it with you

**Comment by meforce** [comment]
Hi, mertcetin.official@gmail.com you can mail.

**Comment by darbanhandrew** [comment]
i am so sorry for late answering, do you still need it ? i can email it now.

**Comment by meforce** [comment]
> i am so sorry for late answering, do you still need it ? i can email it now.

Yup. please send. I am waiting

**Comment by meforce** [comment]
### Solved
I realized there is a simple solution.

<img width="250px" src="https://i.ibb.co/pZ4jjTt/Screenshot-1628169876.png" alt="Screenshot-1628169876" border="0" ><img width="250px" src="https://i.ibb.co/N2mTBpD/Screenshot-1628169756.png" alt="Screenshot-1628169756" border="0">


**package.json > Capacitor 3+**
```
"@capacitor-community/camera-preview": "^1.2.1",
"@capacitor/android": "^3.0.1",
"@capacitor/cli": "^3.0.1",
"@capacitor/core": "^3.0.1",
```
**Use latest version**
`npm install @capacitor-community/camera-preview@latest`

Capacitor Camera Preview Changes in Connections

```
import { Plugins } from "@capacitor/core"
const { CameraPreview } = Plugins;
import { CameraPreviewOptions, CameraPreviewPictureOptions, CameraPreviewFlashMode } from '@capacitor-community/camera-preview';
```

Other codes can remain the same.

I added **androidmanifest.xml** accesses and it works fine.

```
<!-- Permissions -->
<uses-permission android:name="android.permission.CAMERA" />
<uses-feature android:name="android.hardware.camera" />
<uses-feature android:name="android.hardware.camera.autofocus" android:required="false" />
```

<img width="250px" src="https://i.ibb.co/XD8BPSk/Screenshot-1628170494.png" alt="Screenshot-1628170494" border="0">

**Comment by meforce** [comment]
This workaround is unofficial workaround
