### ISSUE TITLE
Zoom

### ISSUE THREAD

**Issue by mehdis34** [capacitor-community/camera-preview#158]
Hello !
 Thanks for this fantastic library.
 I have to use the zoom.  but I don't know at all how to do with this library.  Does anyone have a solution?
 Thank you in advance

**Comment by lauritaila** [comment]
hi <3 
is the height and width if you erase that in yhe CameraPreviewOptions and the camera should look fine.

**Comment by pbowyer** [comment]
Hi @mehdis34 pinch and zoom is now present in version 2.1.0. Have fun using it!
