### ISSUE TITLE
Property 'startRecordVideo' does not exist on type 'CameraPreviewPlugin'.ts

### ISSUE THREAD

**Issue by ghost** [capacitor-community/camera-preview#163]
`Property 'startRecordVideo' does not exist on type 'CameraPreviewPlugin'.ts(2339)`

Same problem. What's the solution. I looked at the entire code base. there is no such function.
Is this feature not available?

**Comment by iverson-deviana** [comment]
I have the same problem too

**Comment by AKempente** [comment]
Any updates about this issue??. 

I am having the same problem where the app crashes when calling this method.

Im using Capacitor 4. Any suggestions would be much appreciated.
