### ISSUE TITLE
iPhone field of view different in Camera Preview vs captured photo

### ISSUE THREAD

**Issue by pbowyer** [capacitor-community/camera-preview#171]
**Describe the bug**
When I take a photo on certain iPhone models, what I see isn't what is captured in the photo.

**To Reproduce**
1. Fill the camera preview with something
2. Take a picture
3. See if the picture is filled like the camera preview was (it is on Android)

**Expected behavior**
If something fills 90% of the camera preview on-screen, it should fill 90% of the width of the photo.

**Screenshots**
Here's a video showing the preview and then the image
https://user-images.githubusercontent.com/89852/137171083-8c0bb400-2f7d-428b-8691-99e03e202c95.mp4
I expect both to be the same, but the photo is much more wide angled.

**Smartphone (please complete the following information):**
Reproduced on
 - iPhone XS
 - iPhone 12
 - iPhone 7
all running iOS 14.7

**Additional context**
I'm using #162 in these tests. The code (from an Ionic Vue app) is:
```ts
  methods: {
    async start() {
      const flashMode: CameraPreviewFlashMode = "torch";
      await cameraPreview.start({
        toBack: true,
        parent: "cameraHere",
        position: "rear",
      });
      this.cameraLoaded = true;
      try {
        await cameraPreview.setFlashMode({ flashMode: flashMode });
      } catch (e) {
        // The web platform doesn't support setting flashMode
      }
    },
    async capture() {
      // Currently CameraPreview's ImageResult has a different structure for Android and iOS 🤦‍♂️ so type as :any
      const img: any = await cameraPreview.capture({});
      // When the structure is unified, won't need to check for .value or .image - only one will be present
      const imgString =
        "data:image/jpeg;charset=utf-8;base64," +
        ("value" in img ? img.value : img.image);
      this.img = imgString;
      await cameraPreview.stop();
    },
  },
```

**Comment by arcadius** [comment]
> Okay, solved.
> 
> On iOS the camera preview is made fullscreen using [`AVLayerVideoGravity.resizeAspectFill`](https://github.com/capacitor-community/camera-preview/blob/master/ios/Plugin/CameraController.swift#L159). If the camera doesn't have the same ratio as the screen, this crops the camera preview to fit the screen.
> 
> When the photo is taken this cropping isn't applied and the full photo is returned. So what you see on screen will not match what is captured in the photo.
> 
> The iOS camera app shows the entire picture and puts black bars above/below the camera preview. This can be done in Camera Preview by changing `AVLayerVideoGravity.resizeAspectFill` to `AVLayerVideoGravity.resizeAspect`. However I did not find an easy way to control where the black bars are placed and move the preview from the center of the screen to the top or bottom of the screen.
> 
> What can we do in the plugin to improve this?
> 
> * Add cropping options so what's shown on-screen is what's captured
> * Add support for `AVLayerVideoGravity.resizeAspect` and controlling where on-screen the preview appears

Hello @pbowyer 
Thanks for the analysis.
This issue still persists and on iOS, the capture dimensions are not the same as the one of the preview.
This is similar to
https://github.com/capacitor-community/camera-preview/issues/180

Having a "crop" functionality in place would be helpful
