### ISSUE TITLE
Plugin defaulting to web implementation on Android

### ISSUE THREAD

**Issue by rbcarlos** [capacitor-community/camera-preview#172]
**Describe the bug**
The plugin defaults to web implementation on Android. This causes the capture to work normally, but the flip or flash do not work giving:
```
Error: flip not supported under the web platform
```

Furthermore, the camera on my phone defaults to the wide-angle camera (not sure if this is the expected behaviour) and is blurry (tap to focus does not work either).

**To Reproduce**
This is what my MainActivity.java looks like:
```
import com.ahm.capacitor.camera.preview.CameraPreview;

public class MainActivity extends BridgeActivity {
    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        this.init(savedInstanceState, new ArrayList<Class<? extends Plugin>>() {{
            // Additional plugins you've installed go here
            // Ex: add(TotallyAwesomePlugin.class);
            add(CameraPreview.class);
        }});
    }
}
```

Furthermore, in my component I instantiate the CameraPreview and call the flip method:
```
    const cameraPreviewOptions: CameraPreviewOptions = {
      position: 'rear',
      //toBack: true,
      parent: 'cameraPreview',
      className: 'cameraPreview'
    };
    CameraPreview.start(cameraPreviewOptions);

      flipCamera(){
           CameraPreview.flip();
      }
```

**Expected behavior**
When running the app on Android, the plugin should default to the Android implementation.
It would be nice if the rear orientation defaulted to the "normal" rear camera and the touch to focus would work as itended.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS 11.2.3
 - Browser safari

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S10 Plus
 - OS: Android 11
 - Browser: Google Chrome
 - Version 94.0.4606.85

**Comment by pbowyer** [comment]
Closing due to lack of feedback.
