### ISSUE TITLE
iOS - X Y options ignored 

### ISSUE THREAD

**Issue by juanpirezsarquis** [capacitor-community/camera-preview#188]
Parameters x, y passed to the plugin are ignored in iOS.
I'm using version **2.0.0-beta.2**,

It always start the preview on position (0,0).

Line 99 https://github.com/capacitor-community/camera-preview/blob/capacitor-3/ios/Plugin/Plugin.swift
`self.previewView = UIView(frame: CGRect(x: 0, y: 0, width: self.width!, height: height))`

Should be:
`self.previewView = UIView(frame: CGRect(x:` **self.x ?? 0** `, y: `**self.y ?? 0**`, width: self.width!, height: height))`

PR: https://github.com/capacitor-community/camera-preview/pull/187

**Comment by pbowyer** [comment]
Thank you for reporting this issue and especially for providing a PR. I've closed this by merging the pull request 👍
