### ISSUE TITLE
ios NSMicrophoneUsageDescription reuested when not needed

### ISSUE THREAD

**Issue by moblizeit** [capacitor-community/camera-preview#191]
**Describe the bug**
on ios with capacitor 3 when i open the cameraPreview my app fails with error
"The app's Info.plist must contain an NSMicrophoneUsageDescription key with a string value explaining to the user how the app uses this data."

I only need to capture pictures and do not require sound. so not sure why it is mandatory? how do i disable for this?

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by pbowyer** [comment]
Thanks for reporting, this is really annoying I agree! I haven't found why Microphone usage is required; hoping someone in the community can advise and provide a pull request to fix 👍

**Comment by ryaa** [comment]
This bug has already been fixed for Android (see https://github.com/capacitor-community/camera-preview/issues/65#issuecomment-783324468)

**Comment by keeskraak** [comment]
I also run into this problem on iOS. I only need to take pictures, but somehow access to the microphone is needed.

Is there any update on this issue?

**Comment by pbowyer** [comment]
This is fixed in version 3.1.0 released today 🥳
