### ISSUE TITLE
Deprecated Code

### ISSUE THREAD

**Issue by cpgb85** [capacitor-community/camera-preview#197]
When using this plugin on the web, these  are the warnings I get just by triggering the CameraPreview.start() function, ignore the error: 

![image](https://user-images.githubusercontent.com/21691341/150276408-eee05f8e-3dba-4aa4-a22d-cf8eb67f6996.png)

Any idea what this is? Nobody else seems to be mentioning this.

**Comment by z0lo13** [comment]
@pbowyer any updates on this?

**Comment by pbowyer** [comment]
@z0lo13 Not from me sorry; I use this plugin on iOS and Android but not the web, so that gets less maintenance than the rest does.
