### ISSUE TITLE
Compiling for iOS 11.0, but module 'Capacitor' has a minimum deployment target of iOS 12.0

### ISSUE THREAD

**Issue by DiegoRodriguez93** [capacitor-community/camera-preview#198]
I am not being able to compile in ios with these versions
```
camera-preview: version "1.2.1";
capacitor: version "3.3.3";
```

any solutions?

**Comment by Raphael-Schulz** [comment]
If you want to use the camera-preview plugin with Capacitor 3 you will have to wait for this PR to be released.
https://github.com/capacitor-community/camera-preview/pull/183

**Comment by pbowyer** [comment]
v2.0.0 was released 10 minutes ago so you're good to go. It's compatible with Capacitor 3, so Please try again using this version!
