### ISSUE TITLE
Capacitor camera not opening on android 12 pixel 4a

### ISSUE THREAD

**Issue by fahad-cinnova** [capacitor-community/camera-preview#214]
import { Plugins } from '@capacitor/core';

const { Camera } = Plugins;

I'm using this code for capture the image in ionic angular :

  const capturedPhoto = await Camera.getPhoto({
      resultType: CameraResultType.Uri,
      source: CameraSource.Prompt,
      quality: 100
    });

These are the version i'm using :
    "@ionic-native/core": "^5.0.0",
    "@ionic/angular": "^5.0.0",

Google pixel 4a (android version 12) not opening the camera for capture the image.
So anyone have the solution for this ???

**Comment by pbowyer** [comment]
@fahad-cinnova Sorry to hear you're having problems. Unfortunately you have asked this question in the wrong repository: this is the `camera-preview` plugin not the `camera` plugin.

Please go to https://github.com/ionic-team/capacitor-plugins#readme and ask for support.
