### ISSUE TITLE
Camera is not running error (intermittent; happens on Android only)

### ISSUE THREAD

**Issue by ryaa** [capacitor-community/camera-preview#224]
**Describe the bug**
Camera is not running error is thrown/displayed intermittently. The problem seems to occur on Android only. 

**To Reproduce**
This is intermittent but when the app starts the camera (using this plugin start method) and immediately after that invokes other plugin methods (for example getSupportedFlashModes) _camera not running_ error occurs from time to time.

**Expected behavior**
No error must occur

**Screenshots**
![Screenshot_20220526-053441_BOSS811](https://user-images.githubusercontent.com/3608222/170419297-706c8f62-2774-4ece-8f22-7d566816dcd3.jpg)

**Smartphone (please complete the following information):**
 - Device: Samsung A30
 - OS: Android 11

**Additional context**
See the detailed explanation here https://github.com/ryaa/camera-preview/blob/5910c0fdd7f70fecbbe8937e8dabea24fd8fe8b6/android/src/main/java/com/ahm/capacitor/camera/preview/CameraPreview.java#L369
This PR should fix it https://github.com/capacitor-community/camera-preview/pull/223

**Comment by pbowyer** [comment]
Thanks for the PR, closing this ticket as it's now merged 👍
