### ISSUE TITLE
Capacitor WebPlugin "CameraPreview" config object was deprecated in v3 and will be removed in v4.

### ISSUE THREAD

**Issue by kieranbarlow** [capacitor-community/camera-preview#243]
**Describe the bug**
Capacitor WebPlugin "CameraPreview" config object was deprecated in v3 and will be removed in v4.

**Comment by 5hee75** [comment]
I have also seen this warning and came looking for a bit more context.  Is web support for the plugin being removed in v4?

**Comment by Max-Millerr** [comment]
"Capacitor WebPlugin "CameraPreview" config object was deprecated in v3 and will be removed in v4."

Does that mean the plugin can no longer be used?

**Comment by pbowyer** [comment]
I'm hoping someone who uses this plugin or Capacitor on the web can jump in, as I only use it on Android/iOS

**Comment by DrDaxter** [comment]
Hi, same problem here. I'm using: capacitor/core": "5.2.2", and capacitor-community/camera-preview": "^5.0.0". the warning still appears 😕
