### ISSUE TITLE
Capacitor 4 support

### ISSUE THREAD

**Issue by ivansglazunov** [capacitor-community/camera-preview#246]
We are forced to switch to capacitor 4. How can I help implement the version for capacitor 4?
Is there currently a branch or fork with partial support? Can I help develop it?

**Comment by pbowyer** [comment]
Hi @ivansglazunov there is a pull request for this already - are you able to test it for me please?
https://github.com/capacitor-community/camera-preview/pull/244

**Comment by sergio-asenjo** [comment]
Are there news about this?

**Comment by pbowyer** [comment]
The patch worked great; I've released v4.0.0 today which works with Capacitor 4
