### ISSUE TITLE
Doesn't work on iOS

### ISSUE THREAD

**Issue by joeyfigaro** [capacitor-community/camera-preview#33]
Using ionic + react and running on physical device. It asks for permission to use the camera but then nothing happens—works perfectly on the web.

**Comment by PIXPOINT** [comment]
I can confirm. Works on Android, but not iOS on a device. Did anyone find a solution?

**Comment by GreenRidingHood** [comment]
@joeyfigaro  @PIXPOINT  any solution
normally https://github.com/cordova-plugin-camera-preview/cordova-plugin-camera-preview i used that in my @ionic/react capacitor ios app, but ios not worked (superview issue) and come to that plugin(according to issue and fix suggestions https://github.com/ionic-team/capacitor/issues/1732).. still not working ios
now crushing at cameraPreview.stop()

**Comment by arielhernandezmusa** [comment]
@joeyfigaro I have it working on iOS 14 with ionic+react, can you post details about your problem?
