### ISSUE TITLE
Import CameraPreview class

### ISSUE THREAD

**Issue by PIXPOINT** [capacitor-community/camera-preview#35]
How do I import the CameraPreview class into the MainAcitify.java? I am getting an error:

error: cannot find symbol add(CameraPreview.class);

**Comment by koczka** [comment]
What was the solution?

**Comment by PIXPOINT** [comment]
Add:
` import com.ahm.capacitor.camera.preview.CameraPreview;`

in MainAcitify.java

**Comment by thenaim** [comment]
@PIXPOINT, not working.
`error: package com.ahm.capacitor.camera.preview does not exist import com.ahm.capacitor.camera.preview.CameraPreview;`

any idea?

**Comment by PIXPOINT** [comment]
@thenaim i don't use this plugin anymore. I switched to this:
https://github.com/cordova-plugin-camera-preview/cordova-plugin-camera-preview

**Comment by thenaim** [comment]
@arielhernandezmusa

**Comment by bravoivang** [comment]
> @thenaim i don't use this plugin anymore. I switched to this:
> https://github.com/cordova-plugin-camera-preview/cordova-plugin-camera-preview

That plugin doesnt work well. You cant put html elements infront of the preview. There is a bug open related to that
