### ISSUE TITLE
Flash Mode not working as expected in CameraPreview on iPhone 16, iOS 18.1.1 &  Google Pixel 5, Android 14

### ISSUE THREAD

**Issue by juliaheller** [capacitor-community/camera-preview#353]
**Describe the bug**
The setFlashMode function does not work as expected. When toggling the flash modes, only the “torch” mode actually activates the flashlight, while “on” and “auto” do nothing. I tried just to initially set to off and then switch to "on" and back and nothing happens. For debugging I switch through all flashModes. 

**To Reproduce**
	1.	Open the camera preview
	2.	Attempt to toggle the flash mode by calling the setFlashMode method with “on”, “off”, "torch" or “auto”.
	3.	Observe that the flashlight does not activate unless the mode is set to “torch”.

**Expected behavior**
The flashlight should turn on when the flash mode is set to “on”.  There should be a method to get the current flashMode from the device.

**Code**
```
protected launchCamera(): void {
    setTimeout(async () => {
      if (this.cameraPreview) {
        const cameraPreviewOptions: CameraPreviewOptions = {
          position: 'rear', // 'front' or 'rear'
          parent: 'cameraPreview',
          className: 'camera-preview',
          width: window.screen.width,
          height: window.screen.height,
          toBack: true, // Display the camera preview behind the HTML
          disableAudio: true,
          enableZoom: true,
        };
        try {
          await CameraPreview.start(cameraPreviewOptions);
          this.isLoading.set(false);
          // Get supported flash modes
          const flashModes = await CameraPreview.getSupportedFlashModes();
          this.supportedFlashModes.set(flashModes.result);

          // Set default flash mode if supported
          if (this.supportedFlashModes().includes('off')) {
            this.currentFlashMode = 'off';
            console.warn('Flash modes:', this.supportedFlashModes(), 'Current flash mode:', this.currentFlashMode);
            setTimeout(async () => {
              await CameraPreview.setFlashMode({ flashMode: this.currentFlashMode });
              this.flashModeIsLoading.set(false);
            }, 500);
          } else if (this.supportedFlashModes().length > 0) {
            this.currentFlashMode = this.supportedFlashModes()[0] || 'off';
            console.warn('Flash modes:', this.supportedFlashModes(), 'Current flash mode:', this.currentFlashMode);
            await CameraPreview.setFlashMode({ flashMode: this.currentFlashMode });
            this.flashModeIsLoading.set(false);
          }

          this._cdr.markForCheck(); // Trigger change detection
        } catch (error) {
         // error handling
        }
      }
    }, 500); // Delay to ensure the camera preview element is rendered
  }
  

/**
   * Changes the flash mode of the camera preview (by button click)
   * @protected
   * @returns Promise that resolves when the flash mode is changed.
   */
  protected async changeFlashMode(): Promise<void> {
    const flashModes = this.supportedFlashModes();
    const currentIndex = flashModes.indexOf(this.currentFlashMode);
    const nextIndex = (currentIndex + 1) % flashModes.length;
    const nextMode = flashModes[nextIndex] || 'off';

    console.warn('Attempting to change flash mode to:', nextMode);

    try {
      await new Promise((resolve): void => {
        setTimeout(resolve, 300);
      }); // Add a delay
      await CameraPreview.setFlashMode({ flashMode: nextMode });
      console.warn('Flash mode successfully set to:', nextMode);
      this.currentFlashMode = nextMode; // Update only if successful
    } catch (error) {
      console.error('Error while changing flash mode:', error);
    } finally {
      this.flashModeIsLoading.set(false);
      this._cdr.markForCheck();
    }
  }
  
```

Logs:
// ⚡️  To Native ->  CameraPreview start 21004844
// ⚡️  TO JS undefined
// ⚡️  To Native ->  CameraPreview getSupportedFlashModes 21004845
// ⚡️  TO JS {"result":["off","on","auto","torch"]}
// ⚡️  [warn] - Flash modes: ["off","on","auto","torch"] Current flash mode: off
// ⚡️  To Native ->  CameraPreview setFlashMode 21004846
// ⚡️  TO JS undefined
  // changing the flashMode: [warn] - Attempting to change flash mode to: on
  // ⚡️  To Native ->  CameraPreview setFlashMode 21004847
  // ⚡️  TO JS undefined
  // ⚡️  [warn] - Flash mode successfully set to: on
  // ⚡️  [debug] - #TT post timeslot: 29.998 feature feed | studysetId undefined
  // ⚡️  [warn] - Attempting to change flash mode to: auto
  // ⚡️  To Native ->  CameraPreview setFlashMode 21004848
  // ⚡️  TO JS undefined
  // ⚡️  [warn] - Flash mode successfully set to: auto
  // ⚡️  [warn] - Attempting to change flash mode to: torch
  // ⚡️  To Native ->  CameraPreview setFlashMode 21004849
  // ⚡️  TO JS undefined
  // ⚡️  [warn] - Flash mode successfully set to: torch

**Smartphone (please complete the following information):**
	•	Device: iPhone 16,  Google Pixel 5
	•	OS: iOS 18.1.1, Android 14

**Additional context**
We tested it on two devices. Only "torch" activates the flashlight

**Comment by ryaa** [comment]
I will take a look asap

**Comment by ryaa** [comment]
I tested on  iPhone 15, iOS 18.1.1 and Samsung A53 with Android 14 and everything works as expected. All the flash modes (on, off, auto, torch) works as expected.

@juliaheller Can you please provide a GitHub repository with the sample app demonstrating the problem?

**Comment by juliaheller** [comment]
Unfortunately, I cannot share our repository. It's private.
Do you have an idea what could hinder the CameraPreview.setFlashMode() - like some special config or permission?

**Comment by juliaheller** [comment]
I don't know if I have enough time to set up a demo app. Could you share your demo so that I can test on my device?

**Comment by ryaa** [comment]
Closing as everything works as expected. No changes are planned.
