### ISSUE TITLE
iOS Camera Output not Visible

### ISSUE THREAD

**Issue by scanlop-pses** [capacitor-community/camera-preview#53]
**Describe the bug**
Using iOS 13.7 the camera output appears to be a white screen. It seems to be hidden behind this. A picture can still be taken however the preview is not visible. No errors are being generated.

**To Reproduce**
1.  Build Project
2. Install on Device
3. Open Camera
4. White screen
5. Take Picture
6. No Errors

**Expected behavior**
Camera preview should appear. 

**Screenshots**
![iimage](https://user-images.githubusercontent.com/71489201/93575756-ed001080-f991-11ea-8ffd-3d02b64ae443.jpg)

**Smartphone (please complete the following information):**
 - Device: iPhone 11
 - OS: iOS 13.7

**Additional context**
No issues reported on Android.

Background is set to transparent.
`
ion-content {
  --background: transparent!important
}
`

**Comment by flaupi** [comment]
I see the same behaviour on an iPhone 8 with iOS 13.51.

**Comment by davehearne** [comment]
I have the same issue with iOS 13.7 on iPhone X
Working on Android

**Comment by flaupi** [comment]
My implementation also works on Android :thinking:

**Comment by sarahizabel7** [comment]
I have the same issue on Iphone 11. Even after the merged fix https://github.com/capacitor-community/camera-preview/pull/69

If I use the `toBack : true` option, the camera preview don't show up.
It only shows if I use `toBack : false`.

Can anyone help?
