### ISSUE TITLE
Support exifInternface for api level inferior to 24

### ISSUE THREAD

**Issue by shangeeee** [capacitor-community/camera-preview#66]
**Describe the bug**
Just after capturing an image the application crashes

**To Reproduce**

**Expected behavior**

**Desktop:**
 Working well on destktop. Thank for that

**Smartphone:**
 - Device: LG
 - OS: android 6
 - Browser: Chrome
 - Version: 85

**Comment by arielhernandezmusa** [comment]
I can't make work a capacitor app on android 6 API 23

**Comment by shangeeee** [comment]
> I can't make work a capacitor app on android 6 API 23

Thanks you for answering. I used the androidx variant of the package and everything went good.
