### ISSUE TITLE
Plugin type inference is not (always) working

### ISSUE THREAD

**Issue by joepb** [capacitor-community/camera-preview#91]
**Describe the bug**
When importing the plugin in the default Capacitor style, the type inference is not correctly working.

**To Reproduce**
Implement  a component with:
```ts
import { Plugins } from "@capacitor/core";
import "@capacitor-community/camera-preview";

const { CameraPreview } = Plugins;
```
and the type of `CameraPreview` will be `any`.

**Expected behavior**
The inferred type of `CameraPreview` should be `CameraPreviewPlugin`

**Screenshots**
![image](https://user-images.githubusercontent.com/5315418/106393266-94488600-640f-11eb-9bf1-c503d6658738.png)

**Additional context**
Not sure why this is a problem. Other plugins use exactly the same inference strategy but they do succeed. I thought it was because of the `"latest"` version in the package.json, but doesn't seem to fix it reliably.

**Comment by pbowyer** [comment]
I'm closing this ticket because our focus is now on Capacitor 3 and I think this should be improved. If it still happens with `camera-preview:2.0.0` please reopen this issue or create a new one.
