### ISSUE TITLE
Add changelog

### ISSUE THREAD

**Issue by mesqueeb** [capacitor-community/camera-preview#95]
I was wondering if it's safe to update to `1.2.0` but I can't find a changelog : )

I think a changelog would be a great addition to this plugin! < 3

**Comment by ryaa** [comment]
This will be very useful. Here is a good example - see https://github.com/dpa99c/cordova-diagnostic-plugin/blob/master/CHANGELOG.md

**Comment by jcesarmobile** [comment]
The project now has a CHANGELOG file, so closing
https://github.com/capacitor-community/camera-preview/blob/master/CHANGELOG.md
