### ISSUE TITLE
Add a License

### ISSUE THREAD

**Issue by JarWarren** [capacitor-community/camera-preview#98]
This repository does not contain a license. [Github's documentation](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository#choosing-the-right-license):

> You're under no obligation to choose a license. However, without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work. If you're creating an open source project, we strongly encourage you to include an open source license.

**Comment by arielhernandezmusa** [comment]
License added https://github.com/capacitor-community/camera-preview/blob/master/LICENSE
